### ISSUE TITLE
Apache Arrows streams only ~5 million records out of ~7 million records in the table

### ISSUE THREAD

**Issue by petr-ponomarenko** [googleapis/python-bigquery-storage#111]
When I use streaming of data from BQ table with 7 million records using Apache Arrows I get only about 5 million records. Other methods of getting data from that table into pandas work fine. I am following this example with one stream https://github.com/googleapis/python-bigquery-storage/blob/6254bf2a588e69e2175df1c67edb514655d93e9d/samples/to_dataframe/main_test.py#L130-L139

**Comment by tswast** [comment]
We probably need to update that code sample to explicitly request only one stream.

**Comment by tswast** [comment]
I've sent https://github.com/googleapis/python-bigquery-storage/pull/114 which adds `max_stream_count=1` to the `create_read_session` call. I believe the issue you're encountering is because additional streams are created, which are assigned the rows which you are missing.
