### ISSUE TITLE
system tests expect public_samples_copy dataset but don't provision it

### ISSUE THREAD

**Issue by shollyman** [googleapis/python-bigquery-storage#14]
tests/system/test_reader.py:

```
shakespeare_ref = bigquery_storage_v1beta1.types.TableReference()
shakespeare_ref.project_id = project_id
shakespeare_ref.dataset_id = "public_samples_copy"
shakespeare_ref.table_id = "shakespeare"
```

Clean this up, so we at least probe and setup.  Due to setup time we should avoid full setup/teardown.

**Comment by meredithslota** [comment]
Found in https://github.com/googleapis/python-bigquery-storage/blob/master/tests/system/v1beta1/test_reader_v1beta1.py but NOT in https://github.com/googleapis/python-bigquery-storage/blob/master/tests/system/v1/test_reader_v1.py - looks like the relevant section was refactored and now uses `local_shakespeare_table_reference` instead.

**Comment by meredithslota** [comment]
@tswast and @steffnay is there anything else left to do here or does #74 suffice to fix this?

**Comment by tswast** [comment]
https://github.com/googleapis/python-bigquery-storage/blob/master/tests/system/assets/public_samples_copy.sql should be enough for someone to figure out how to create this table.
