### ISSUE TITLE
google-cloud-bigquery-storage is causing conflict on Dataproc 1.5-debian10 with optional packages: ANACONDA and JUPYTER

### ISSUE THREAD

**Issue by chanirban** [googleapis/python-bigquery-storage#261]
On Dataproc 1.5-debian10, optional packages ‘ANACONDA and JUPYTER’ are not working with the Python packages - "google-cloud-bigquery **google-cloud-bigquery-storage** google-cloud-storage pandas pyarrow" as a startup script and we think **google-cloud-bigquery-storage ** is causing the conflict. Surprisingly, the same packages and optional packages works without issues on Dataproc 1.3 and 1.4-debian10.
Is there any guidance available that, on Dataproc 1.5-debian10, Python Packages google-cloud-bigquery-storage  of version xxx are compatible with optional packages ANACONDA and JUPYTER.

**Comment by tswast** [comment]
Do you have any additional information about which dependency is causing the conflict?

There are some known incompatibilities between newer versions of pyarrow and Spark 2.x. https://spark.apache.org/docs/latest/api/python/user_guide/arrow_pandas.html#compatibility-setting-for-pyarrow-0-15-0-and-spark-2-3-x-2-4-x Is this what you're hitting?
