### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 request failed: data format unspecified

### ISSUE THREAD

**Issue by karan-kumar-by** [googleapis/python-bigquery-storage#264]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: 3.6.9
  - pip version: 21.2.2
  - `google-cloud-bigquery-storage` version: 2.6.2

#### Steps to reproduce

  1. Code example 1 - It is working when I am using google-cloud-bigquery-storage==0.8.0
  2. Code example 2 - It is not working when I am using google-cloud-bigquery-storage==2.6.2

#### Code example

```python
# example 1 - Env Info: 
google==2.0.3
google-api-core==1.23.0
google-api-python-client==1.8.0
google-apitools==0.5.28
google-auth==1.22.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud==0.34.0
google-cloud-bigquery==1.24.0
google-cloud-bigquery-storage==0.8.0
google-cloud-bigtable==1.0.0
google-cloud-container==2.1.0
google-cloud-core==1.3.0
google-cloud-datastore==1.7.4
google-cloud-monitoring==0.34.0
google-cloud-pubsub==1.3.1
google-cloud-storage==1.26.0
google-pasta==0.2.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0

# Code -
from google.cloud import bigquery_storage_v1beta1
from google.cloud import bigquery

project_id = 'devlopment'
#
# The read session is created in this project. This project can be
# different from that which contains the table.
bq_client=bigquery.Client()

query="SELECT ITEM_ID, DATE, QUANTITY, CREATE_TIMESTAMP FROM DEMO.INVENTORY_SNAPSHOT WHERE LOCATION_ID = 2 LIMIT 10"

query_job = bq_client.query(query)
result = query_job.result()

client = bigquery_storage_v1beta1.BigQueryStorageClient()
table_ref = bigquery_storage_v1beta1.types.TableReference()
table_ref.project_id = query_job.destination.project
table_ref.dataset_id = query_job.destination.dataset_id
table_ref.table_id = query_job.destination.table_id

# Set a snapshot time if it's been specified.
modifiers = None

parent = "projects/{}".format(query_job.destination.project)
session = client.create_read_session(
    table_ref,
    parent,
    table_modifiers=modifiers,
    requested_streams=5,
    format_=bigquery_storage_v1beta1.enums.DataFormat.DATA_FORMAT_UNSPECIFIED,
    sharding_strategy=(bigquery_storage_v1beta1.enums.ShardingStrategy.SHARDING_STRATEGY_UNSPECIFIED),
)  # API request.

reader = client.read_rows(
    bigquery_storage_v1beta1.types.StreamPosition(stream=session.streams[0])
)

# pip install google-cloud-bigquery-storage[fastavro]
rows = reader.rows(session)

for row in rows:
    print(f"{row['DATE']} - {type(row['DATE'])}")
    print(row)

```

```
# example 2 - Env Info: 
google==3.0.0
google-api-core==1.31.1
google-api-python-client==1.12.8
google-apitools==0.5.31
google-auth==1.34.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.5
google-cloud==0.34.0
google-cloud-aiplatform==0.7.1
google-cloud-bigquery==2.20.0
google-cloud-bigquery-storage==2.6.2
google-cloud-bigtable==1.7.0
google-cloud-build==2.0.0
google-cloud-container==2.3.1
google-cloud-core==1.7.2
google-cloud-datastore==1.15.3
google-cloud-dlp==1.0.0
google-cloud-language==1.3.0
google-cloud-monitoring==2.0.1
google-cloud-profiler==3.0.5
google-cloud-pubsub==1.7.0
google-cloud-spanner==1.19.1
google-cloud-storage==1.41.0
google-cloud-videointelligence==1.16.1
google-cloud-vision==1.0.0

# Code -

from google.cloud import bigquery_storage_v1beta2
from google.cloud import bigquery

project_id = 'development'
#
# The read session is created in this project. This project can be
# different from that which contains the table.
bq_client=bigquery.Client()

query="SELECT ITEM_ID, DATE, QUANTITY, CREATE_TIMESTAMP FROM DEMO.INVENTORY_SNAPSHOT WHERE LOCATION_ID = 2 LIMIT 10"

query_job = bq_client.query(query)
result = query_job.result()

client = bigquery_storage_v1beta2.BigQueryReadClient()

_table = f"projects/{query_job.destination.project}/datasets/{query_job.destination.dataset_id}" \
         f"/tables/{query_job.destination.table_id}"
parent = f"projects/{query_job.destination.project}"

requested_session = bigquery_storage_v1beta2.types.ReadSession()
requested_session.table = _table
requested_session.data_format = bigquery_storage_v1beta2.types.DataFormat.DATA_FORMAT_UNSPECIFIED

read_session = client.create_read_session(parent=parent, read_session=requested_session, max_stream_count=5)

reader = client.read_rows(read_session.streams[0].name)

rows = reader.rows(read_session)

for row in rows:
    print(f"{row['DATE']} - {type(row['DATE'])}")
    print(row)

```

#### Stack trace
Traceback (most recent call last):
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "request failed: data format unspecified"
	debug_error_string = "{"created":"@1628264366.944590000","description":"Error received from peer ipv6:[2404:6800:4007:82b::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"request failed: data format unspecified","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/1029151/Project/BY-ML/CML/commerce-machine-learning/src/bigquery_storage_v1beta2.py", line 51, in <module>
    read_session = client.create_read_session(parent=parent, read_session=requested_session, max_stream_count=5)
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/cloud/bigquery_storage_v1beta2/services/big_query_read/client.py", line 510, in create_read_session
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/Users/1029151/.pyenv/versions/tf25_tfx/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 request failed: data format unspecified

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by karan-kumar-by** [comment]
@plamut @tswast I can see below class in bigquery_storage_v1beta2/types/stream.py which confirm we can still use DATA_FORMAT_UNSPECIFIED with bigquery_storage_v1beta2

class DataFormat(proto.Enum):
    r"""Data format for input or output data."""
    DATA_FORMAT_UNSPECIFIED = 0
    AVRO = 1
    ARROW = 2

**Comment by tswast** [comment]
This is expected behavior.

The API does not presume a default value for the data format. All protocol buffer enums are expected to have an "unspecified" value for the 0 value: https://developers.google.com/protocol-buffers/docs/style#enums

**Comment by tswast** [comment]
The `beta1` endpoint defaulted to Avro. This is not the case for `v1` or `v1beta2`.

**Comment by karan-kumar-by** [comment]
@tswast Thanks for the quick response.
