### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by arturadib** [googleapis/python-bigquery-storage#30]
The page below encourages us to migrate away from pands-gbq. We did so, but we lost the progress bar (e.g. in Collaboratory) which is an important feature of pandas-gbq particularly when fetching large datasets.

Any plans to add a progress bar for long queries? Thank you!

**Comment by meredithslota** [comment]
@arturadib Which page are you referencing?

**Comment by arturadib** [comment]
Oops sorry here we go:

"Migrating from pandas-gbq"
https://cloud.google.com/bigquery/docs/pandas-gbq-migration

**Comment by tswast** [comment]
We need to update that guide, as it's not necessary to migrate from pandas-gbq unless advanced features like `list_datasets` and `list_models` are required (many operations can be done with INFORMATION_SCHEMA queries these days)

That said, the `to_dataframe` method takes a `progress_bar_type="tqdm"` argument, which will give you the same behavior as pandas-gbq. See: https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.table.RowIterator.html#google.cloud.bigquery.table.RowIterator.to_dataframe

**Comment by tswast** [comment]
https://github.com/googleapis/python-bigquery/issues/343 has been closed, which adds progress bars to `QueryJob.to_dataframe()`
