### ISSUE TITLE
Promoting google-cloud-bigquery-storage to a GA release

### ISSUE THREAD

**Issue by shollyman** [googleapis/python-bigquery-storage#33]
Currently at 0.8.x, intent is to promote major version to 1.x.

## Satisfied
- [x] backend is GA as of [March 02, 2020](https://cloud.google.com/bigquery/docs/release-notes#March_02_2020)
- [x] more than 28 days elapsed since last changes to surface contract

## Open for discussion

- This API supports multiple data serialization methods with convenience methods to simplify user consumption (e.g. dataframe support).  That mechanism continues to evolve and uses dependencies that are pre 1.x, but the API contract itself is GA and stable.  Should this block a 1.x release?

- This library is still publishing with py2.7 support.  Should we drop py2.7 as part of the GA promotion and avoid having to publish another major release, or handle the py2.7 as its own event (and another major release)?

**Comment by shollyman** [comment]
Feedback?  @plamut @tswast @steffnay @busunkim96

**Comment by busunkim96** [comment]
> This API supports multiple data serialization methods with convenience methods to simplify user consumption (e.g. dataframe support). That mechanism continues to evolve and uses dependencies that are pre 1.x, but the API contract itself is GA and stable. Should this block a 1.x release?

If the API contract is stable, it seems appropriate to release as GA.

> This library is still publishing with py2.7 support. Should we drop py2.7 as part of the GA promotion and avoid having to publish another major release, or handle the py2.7 as its own event (and another major release)?

For other GAPICs we've been treating GA and the 2.7 drop as separate events. (2.7 drops are happening with the microgenerator, which explicitly requires 3.6+)

**Comment by danoscarmike** [comment]
SGTM!
