### ISSUE TITLE
Question regarding the "transaction across stream" feature of the BQ storage write API

### ISSUE THREAD

**Issue by GodefroyClair** [googleapis/python-bigquery-storage#355]
Are there any examples of the "transaction across streams" features briefly described in the [GCP documentation about the Storage Write API](https://cloud.google.com/bigquery/docs/write-api#advantages)?
(also interested to know more about the "Stream-level transactions" feature")
Thanks!

**Comment by tswast** [comment]
Regarding "stream-level transactions", we actually already use this feature in the Python code sample here: https://github.com/googleapis/python-bigquery-storage/blob/main/samples/snippets/append_rows_pending.py

By putting the stream in "PENDING" mode, writes are not considered part of the table until the stream is (1) finalized and (2) committed.

Regarding "transaction across streams", I believe this is referring to the fact that you can commit multiple PENDING streams atomically using the BatchCommitWriteStreamsRequest.

**Comment by tswast** [comment]
I believe the intended use case is that you can split a write across multiple workers, each with their own stream. Once all workers have finalized their streams, a batch commit request can be sent to commit all of the writes at once.

**Comment by shollyman** [comment]
Closing this as it's mostly a docs issue rather than a library issue, and those are tracked elsewhere (internally).  Tim's comments are correct regarding the atomicity of commits using mechanisms like `BatchCommitWriteStreams`.
