### ISSUE TITLE
Add a comment in `setup.py` to clarify that `importlib-metadata` is only needed for python 3.7

### ISSUE THREAD

**Issue by parthea** [googleapis/python-bigquery-storage#735]
We should add a comment to `setup.py` to clarify that `importlib-metadata` is only needed for compatibility with python 3.7 

Also, the package name in PyPI is `importlib-metadata` but in setup.py we have `importlib_metadata`

For python 3.7, we use [importlib-metadata](https://pypi.org/project/importlib-metadata/) from PyPI 
For python 3.8, we use [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) which is builtin.

https://github.com/googleapis/python-bigquery-storage/blob/fb0d6f07d4b7582cf01ec98fee3081ec34995603/setup.py#L47

**Comment by xionams** [comment]
assign me?

**Comment by chalmerlowe** [comment]
Closing as finished. See linked fix PR above.
