### ISSUE TITLE
Can I get compressed arrow data directly from gRPC call?

### ISSUE THREAD

**Issue by Tunneller** [googleapis/python-bigquery-storage#794]
I'm using ```bq_storage_client.create_read_session``` with max_streams ~5 and data compression::
```
requested_session = bigquery_storage.types.ReadSession()
requested_session.table = destination_table
requested_session.data_format = bigquery_storage.types.DataFormat.ARROW
requested_session.read_options.arrow_serialization_options.buffer_compression = 
            bigquery_storage.ArrowSerializationOptions.CompressionCodec.LZ4_FRAME
```
It's all working very nicely. 

I'm chasing through the code and can see compressed messages arriving and then somewhere along the chain they get deserialized with to_arrow(). Cool.

However, Arrow now has a class for RunEndEncodedArray and it seems like most of the pieces are in place to go straight from BigQuery to Arrow without the deserialization step.

Would that be straightforward to implement??

**Comment by emkornfield** [comment]
> Would that be straightforward to implement??

This is more a question on if the BQ backend produces Arrow data with this encoding.

I think the main question to answer here is what is the problem that this is trying to solve.  Even if the backend supported producing this data there is no guarantee it would produce it in all case, so LZ4 is still potentially useful, it really depends on what is trying to be optimized.  FWIW the backend also does not as of today produce dictionary encoded data which could also help reduce size.

**Comment by chalmerlowe** [comment]
Based on this discussion, our current staffing, and our current priorities, I am gonna close this as will not fix. If someone wants to generate a PR to implement this, we may be willing to consider it for inclusion, but no guarantees.
